# Generated by Django 5.1 on 2024-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffinservice',
            name='menu',
            field=models.JSONField(),
        ),
    ]
