# Generated by Django 5.1 on 2024-09-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_tiffinservice_meal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffinservice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tiffinservice',
            name='menu_name',
            field=models.CharField(max_length=100),
        ),
    ]
