# Generated by Django 5.1 on 2024-09-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
